myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^(?P<course_no>\d{3,3})/$', views.detail, name='detail'),
        url(r'^addtopic/$', views.addtopic, name='addtopic'),
        url(r'^topics/$', views.topics, name='topics'),
        url(r'^topicdetails/(?P<topic_id>\d*)/$',views.topicdetail, name='topicdetails'),
        url(r'^register/$',views.register,name='register'),
        url(r'^login/$',views.user_login, name='login'),
        url(r'^mycourses/$',views.mycourses, name='mycourses'),
        url(r'^logout/$',views.user_logout, name='logout')
        ]

mysiteS17/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls', namespace = 'myapp')),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator


# Create your models here.

class Author(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    birthdate = models.DateField()
    # age = models.IntegerField()
    city=models.CharField(max_length=100, default="Windsor", blank=True)
    def __str__(self):
        return self.firstname+" "+ self.lastname


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    in_stock = models.BooleanField(default=True)
    numpages=models.IntegerField(default='',validators=[MinValueValidator(50),MaxValueValidator(1000)])
    isbn=models.IntegerField(default=101)

    def __str__(self):
        return self.title


class Student(User):
    PROVINCE_CHOICES = (
        ('AB', 'Alberta'),  # First value is stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    age = models.IntegerField(null=True)
    state=models.CharField(max_length=30,default='delhi')
    def __str__(self):
        return self.first_name +" "+self.last_name




class Course(models.Model):
    course_no = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    textbook = models.ForeignKey(Book)
    students = models.ManyToManyField(Student, blank=True)

    def __str__(self):
        return self.title


class Topic(models.Model):
    subject = models.CharField(max_length=100, unique=True)
    intro_course = models.BooleanField(default=True)
    NO_PREFERENCE = 0
    MORNING = 1
    AFTERNOON = 2
    EVENING = 3
    TIME_CHOICES = (
        (0, 'No preference'),
        (1, 'Morning'),
        (2, 'Afternoon'),
        (3, 'Evening')
    )
    time = models.IntegerField(default=0, choices=TIME_CHOICES)
    num_responses = models.IntegerField(default=0)
    avg_age = models.IntegerField(default=20)
    def __str__(self):
        return self.subject

myapp/forms.py
from django import forms
from myapp.models import Topic
from myapp.models import Topic, Student


class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['subject','intro_course','avg_age','time']
        labels={'subject':'subject','intro_course':'This is an introductory level course','avg_age':'What is your age?','time':'Preferred Time'}
        widgets={'time':forms.RadioSelect}


class InterestForm(forms.Form):
    CHOICES=((1,'Yes'),(0,'No'))
    interested=forms.ChoiceField(widget=forms.RadioSelect,choices=CHOICES)
    age=forms.IntegerField(initial=20)
    comments=forms.CharField(widget=forms.Textarea,required=False,label='Additional Comments')

class StudentForm(forms.ModelForm):
    class Meta:
        model=Student
        fields=['username','password','first_name','last_name','email','age','address','city', 'province','state']


class LoginForm(forms.Form):
    username=forms.CharField(label='username')
    password=forms.CharField(widget=forms.PasswordInput)

myapp/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from myapp.models import Author, Book, Course,Student, Topic
from django.shortcuts import get_object_or_404
from myapp.forms import TopicForm, InterestForm, StudentForm,LoginForm
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    courselist = Course.objects.all().order_by('course_no')[:10]
    return render(request, 'myapp/index.html', {'courselist': courselist})


def about(request):

    return render(request,'myapp/about.html')

def detail(request,course_no):
    #response=HttpResponse()
    course=get_object_or_404(Course,course_no=course_no)
    return render(request,'myapp/detail.html',{'course':course})


def topics(request):
    topiclist = Topic.objects.all()[:10]
    return render(request, 'myapp/topics.html', {'topiclist':   topiclist})

def addtopic(request):
    topiclist = Topic.objects.all()
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.num_responses = 1
            topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form = TopicForm()
    return render(request, 'myapp/addtopic.html', {'form': form,
                                                   'topiclist': topiclist})


def topicdetail(request,topic_id):
    topicdetail=get_object_or_404(Topic,id=topic_id)
    if request.method=='POST':
        interestform=InterestForm(request.POST)
        if interestform.is_valid():
            if interestform.cleaned_data['interested']=='1':
                form=TopicForm(instance=topicdetail)
                topic=form.save(commit=False)
                topic.num_responses=topic.num_responses+1
                topic.avg_age=(topic.avg_age*(topic.num_responses)+interestform.cleaned_data['age'])/(topic.num_responses+1)
                topic.save()
                return HttpResponseRedirect(reverse('myapp:topics'))
            else:
                return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form=InterestForm()
        return render(request,'myapp/topicdetail.html',{'form':form, 'topicdetail':topicdetail})

def register(request):
    if request.method == 'POST':
        stuform = StudentForm(request.POST)
        if stuform.is_valid():
            user=stuform.save(commit=False)
            user.set_password(stuform.cleaned_data['password'])
            user.save()
            return HttpResponseRedirect(reverse('myapp:index'))
    else:
        form=StudentForm()
        return render(request,'myapp/register.html',{'form':form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index')) #
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        form=LoginForm()
        return render(request, 'myapp/login.html',{'requser':request.user,'form':form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))



def mycourses(request):
        l=len(Student.objects.filter(username = request.user.username))
        if l==1:
            student=Student.objects.get(username=request.user.username)
            course=student.course_set.all()

            return render(request, 'myapp/mycourses.html', {'course': course,'flag':0})
        else:

            return render(request, 'myapp/mycourses.html', {'flag': 1})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <p><a href="/myapp/">IndexHard</a></p>

    <p><a href="{% url 'myapp:index' %}">IndexURL</a> </p>

{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<h3>This is a course listing APP.</h3>
<p><a href="/myapp/">IndexHard</a></p>

<p><a href="{% url 'myapp:index' %}">IndexURL</a> </p>
</body>
</html>

myapp/templates/myapp/addtopic.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if topiclist %}
        <h2>List of Topics</h2>
        <ol>
            {% for topic  in topiclist %}
                <li> <a href="/myapp/topicdetails/{{ topic.id }}" >{{ topic.subject}}</a> </li>
            {% endfor %}
        </ol>

 {% else %}
     <strong>There are no available courses!</strong>
 {% endif %}
<h3>To add a new topic:</h3>
    <form method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="submit"/>

    </form>

{% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
        <title>Course Listing APP - {% block title %}Welcome!{% endblock %}</title>
    </head>

    <body>
        <div>
            {% block myhdg %}  <h3>   Welcome {{ user.username }}</h3>
 {% endblock %}
                        {% block body_block %}


            {% endblock %}
        </div>
        <hr >
        <div>
            <ul>

                {% if user.is_authenticated %}
                                       <p><a href="{% url 'myapp:logout' %}">Logout</a>

                     {%  block mycourse %}   <p><a href="{% url 'myapp:mycourses' %}">MyCourses</a> </p> {% endblock %}
                    {% else %}
                        <p><a href="{% url 'myapp:login' %}">Login</a></p>
                    <p>If youre a new user <a href="{% url 'myapp:register' %}">Register</a></p>

                {% endif %}
                <li class="hbar1"><a href="/myapp/about/">Find out about this site</a></li>
                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
                <li class="hbar1"><a href = "{% url 'myapp:topics' %}">Topics</a><br/></li>
            </ul>
        </div>
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <p>course_no: &nbsp;{{ course.course_no }}</p>
    <p>title: &nbsp;{{ course.title }}</p>
    <p>textbook: &nbsp;{{ course.textbook }}</p>
    <h4><a href="{% url 'myapp:index'  %}">Index</a></h4>

{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<p>course_no: &nbsp;{{ course.course_no }}</p>
<p>title: &nbsp;{{ course.title }}</p>
<p>textbook: &nbsp;{{ course.textbook }}</p>
<h4><a href="{% url 'myapp:index'  %}">Index</a></h4>

</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if courselist %}
        <h2>List of Courses</h2>
        <ol>
            {% for course  in courselist %}
                <li> <a href="/myapp/{{ course.course_no }}" >{{ course.title}}</a> </li>
            {% endfor %}
        </ol>

 {% else %}
     <strong>There are no available courses!</strong>
 {% endif %}
{# <h3><a href="{%url 'myapp:about' %}">About page</a></h3>#}

{% endblock %}

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course Listing APP</title>
</head>
<body>
 {% if courselist %}
        <h2>List of Courses</h2>
        <ol>
            {% for course  in courselist %}
                <li> <a href="/myapp/{{ course.course_no }}" >{{ course.title}}</a> </li>
            {% endfor %}
        </ol>

 {% else %}
     <strong>There are no available courses!</strong>
 {% endif %}
 <h3><a href="{%url 'myapp:about' %}">About page</a></h3>

</body>
</html>

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block title %}Login
{% endblock %}
{% block body_block %}
<h2>Login</h2>
    <form method="post">
    {% csrf_token %}
        {{ form.as_table }}
    <input type="submit" value="login">
    </form>

{% endblock %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}
{% block body_block %}

    <h3> You have successfully logged out!!</h3>
{% endblock %}

myapp/templates/myapp/mycourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {%  if flag == 0 %}
    {% if course %}
        <h2>List of Courses</h2>
        <ol>
            {% for c  in course %}
                <li> <a href="/myapp/{{ c.course_no }}" >{{ c.title}}</a> </li>
            {% endfor %}
        </ol>

        {% block mycourse %} {% endblock %}
        {% elif flag == 1 %}
        <p> You are not a student!</p>

    {% endif %}

 {% endif %}
{# <h3><a href="{%url 'myapp:about' %}">About page</a></h3>#}

{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" name="register">
</form>
{% endblock %}

myapp/templates/myapp/topicdetail.html
{% extends 'myapp/base.html' %}
    {% block title %}Topic Detail{% endblock %}

    {% block body_block %}
        <H3>
            TOPIC DETAILS<br>
        </H3>
            Topic name       : {{ topicdetail.subject }}<br>
            No. of responses : {{ topicdetail.num_responses }}<br>
            {% if topicdetail.intro_course == True %}
                Intro course     : YES <br>
            {% else %}
                Intro course     : No <br>
            {% endif %}

            Avg age          : {{ topicdetail.avg_age }} <br>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        </form>

    {% endblock %}

myapp/templates/myapp/topics.html
{% extends 'myapp/base.html' %}

{% block body_block %}

    {% if topiclist %}
        <h2>List of Topics</h2>
        <ol>
            {% for topic  in topiclist %}
                <li> <a href="/myapp/topicdetails/{{ topic.id }}" >{{ topic.subject}}</a> </li>
            {% endfor %}
        </ol>

 {% else %}
     <strong>There are no available topics!</strong>
 {% endif %}
<h3><a href="{%url 'myapp:addtopic' %}">Add Topic</a></h3>

{% endblock %}